import {  Bricolage_Grotesque, Inter, Outfit } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

// Setup Bricolage Grotesque
const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
  weight : '500',
  variable: "--font-bricolage",
});

const outfit = Outfit({
    subsets : ['latin'],
    weight : '500',
    variable: "--font-outfit",


})

export const metadata = {
  title: "Software Chamber",
  description: "Generated by create Tahazzee",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
       className={`${inter.variable} ${bricolage.variable} ${outfit.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
